[package]
name = "payments"
description = "Lily Protocol payment intents with asynchronous creation, settlement and cancellation on Soroban."
keywords.workspace = true
categories.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
rust-version.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
lily-common = { workspace = true }
wallet = { path = "../wallet" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
lily-test-support = { workspace = true }
identity = { path = "../identity" }

[lints]
workspace = true
